development:
  adapter: mysql
  database: example_app_development
  username: root
  password: root
  host: localhost
test:
  adapter: mysql
  database: example_app_test
  username: root
  password: root
  host: localhost
production:
  adapter: mysql
  database: example_app_production
  username: root
  password: root
  host: localhost